### PR TITLE
Remove "this_dynamo" from output names

### PR DESCRIPTION
**Pull request by max-rocket-internet**
This is typo right? It looks and sounds wrong?

## Breaking Changes

Yes

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
I will fix failed CI actions when Anton confirms.

**Comment by antonbabenko** [comment]
No, this is not a typo.

Terraform module may create several resources of the same type and prefix outputs with the resource name is a way to avoid confusion when trying to figure out which exactly resource you are thinking about.

The same principle is implemented in the majority of terraform-aws-modules, for eg:
1. https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/outputs.tf
1. https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/outputs.tf

The exception is the VPC module (and maybe some other) which was ported from https://github.com/terraform-community-modules/tf_aws_vpc and had some users from day-0 already so I was not strict with enforcing this back then (though, I probably should have).

**Comment by max-rocket-internet** [comment]
> the resource name is a way to avoid confusion when trying to figure out which exactly resource you are thinking about.
OK makes sense!

But what is `this_` for? It's meaningless no?

**Comment by antonbabenko** [comment]
`this` is the name of the resource.

For example, `aws_dynamodb_table.this.arn` is `${PROVIDER_NAME}_${RESOURCE_TYPE}.${RESOURCE_NAME}.${RESOURCE_ATTRIBUTE}` which is equal to an output like: `${RESOURCE_NAME}_${RESOURCE_TYPE}_${RESOURCE_ATTRIBUTE}` = `this_dynamodb_table_arn`

**Comment by max-rocket-internet** [comment]
OK! I guess it makes sense in a broader scope, just looks daft to me for modules like this with a single resource 😅

**Comment by max-rocket-internet** [comment]
Thanks for explanation Anton 🙏

**Pull request closed without merging**
